ARG BASE=cgr.dev/chainguard/static

FROM --platform=amd64 cgr.dev/chainguard/go@sha256:93d0850de1bb7a4313eefd4251eb74f20c421559f26c8817b3663fc734d1153d AS build

WORKDIR /build
COPY main.go main.go
RUN CGO_ENABLED=0 go build -o /build/hello main.go

FROM $BASE
COPY --from=build /build/hello /hello
CMD ["/hello"]
